### ISSUE TITLE
EFSA report requested changes

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#351]
- [x] improve loading time of DBView JS
- [x] add page loader animation during loading time of DBView JS
- [x] download option for json file in Report
- [x] simulation parameter in BIRT Report
- [x] dashboard for generic models
- [x] make a workflow with a overview with all services
- [x] online creation of models error?
- [x] remove error when no input parameters are given
- [x] remove warnings in editor js "required"
- [x] checkbox for authors/creators when publish model to Zenodo
- [x] video tutorial for dashboard
- [x] add a readme tab to landingpage/DBView details view
- [ ] remove or declare optional all remaining issues
- [x] add information of support (password reset) to foodrisklabs website
- [x] add link to FSK-Lab software in sandwich menu

**Comment by schuelet** [comment]
Closing this, since no value in keeping it.
