### ISSUE TITLE
CONDA Channel

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#392]
## Goal
- create, populate and maintain a Conda channel containing R (and possibly Python) Packages needed to run models in Model-Repository

## Challenges and open Questions

- [ ] build an installable Conda package
- [ ] build an installable R Conda package from CRAN
 - push conda package to anaconda.org (or other repository)
 - build package for Windows and Linux (x64)
- [ ] build an installable R Conda package from source (packages not available on CRAN)
- [ ] explore if and how individual environments can be pushed to anaconda.org
  - can we make sure that package version x is installable with r-base version y ?
